name: Call RH Service Builder Workflow
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches:
      - master
jobs:
  call-rh-service-builder-workflow:
    name: RH Service Builder
    uses: RallyHereInteractive/github-action-templates/.github/workflows/rh-service-builder.yaml@main
    secrets: inherit
    with:
      helm_only: true
      helm_dir: install/helm/open-match
